# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input:          GFM

# Permalinks
permalink:        pretty

# Setup
title:            Data Science for Agriculture
description:      'How to manage and manipulate data for agricultural research'
url:              http://palderman.github.io/DataSciAg
baseurl:          /DataSciAg
email:            phillip.alderman@okstate.edu

author:
  name:           'Phillip Alderman'
  url:            http://pss.okstate.edu/People/faculty-1/faculty-info/alderman-phillip/phillip-alderman

github:
  repo:           https://github.com/palderman/DataSciAg
  #               Be sure the 'Issues' feature is activated in 'Settings'
